import { existsSync } from "node:fs";
import path from "node:path";

import { PayloadUsers } from "@/cms/collections/PayloadUsers";
import { Proofs } from "@/cms/collections/Proofs";
import { PAYLOAD_DATABASE_SCHEMA, PAYLOAD_ROUTES } from "@/cms/config";

describe("Payload CMS foundation", () => {
  it("keeps the CMS database and routes isolated from existing app surfaces", () => {
    expect(PAYLOAD_DATABASE_SCHEMA).toBe("payload");
    expect(PAYLOAD_ROUTES).toEqual({
      admin: "/cms",
      api: "/cms-api",
      graphQL: "/cms-graphql",
      graphQLPlayground: "/cms-graphql-playground",
    });
  });

  it("mounts GraphQL at the endpoint generated by Payload", () => {
    const graphQLRoute = path.join(
      process.cwd(),
      "src/app/(payload)",
      PAYLOAD_ROUTES.api,
      PAYLOAD_ROUTES.graphQL,
      "route.ts",
    );

    expect(PAYLOAD_ROUTES.api + PAYLOAD_ROUTES.graphQL).toBe(
      "/cms-api/cms-graphql",
    );
    expect(existsSync(graphQLRoute)).toBe(true);
  });

  it("uses a dedicated authenticated collection for Payload editors", () => {
    expect(PayloadUsers.slug).toBe("cms-users");
    expect(PayloadUsers.auth).toBe(true);
    expect(PayloadUsers.admin?.useAsTitle).toBe("email");
  });

  it("defines the editable proof content contract", () => {
    expect(Proofs.slug).toBe("proofs");
    expect(Proofs.admin?.useAsTitle).toBe("title");
    expect(Proofs.fields).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: "title", type: "text", required: true }),
        expect.objectContaining({
          name: "message",
          type: "textarea",
          required: true,
        }),
        expect.objectContaining({
          name: "status",
          type: "select",
          required: true,
        }),
      ]),
    );
  });
});
