# Generated by Django 5.2.1 on 2025-06-10 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_userprofile_profile_picture'), ('accounts', '0003_alter_userprofile_profile_picture'), ('accounts', '0004_alter_userprofile_profile_picture'), ('accounts', '0005_alter_userprofile_profile_picture'), ('accounts', '0006_userprofile_discord_username_userprofile_github_url_and_more'), ('accounts', '0007_alter_userprofile_profile_picture'), ('accounts', '0008_alter_userprofile_profile_picture')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default.webp', null=True, upload_to='profile_pictures/')),
                ('discord_username', models.CharField(blank=True, max_length=100, null=True)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
