# Generated by Django 5.2.1 on 2025-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_discord_username_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='public/profile_pictures/default.webp', null=True, upload_to='public/profile_pictures/'),
        ),
    ]
