# Generated by Django 5.2.1 on 2025-06-10 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_alter_blogpost_options_remove_blogpost_published_and_more'), ('blog', '0003_blogpost_featured_blogpost_super_featured')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
                ('super_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
