# Generated by Django 5.2.1 on 2025-06-08 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
