name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Label PR by size
        uses: codelytv/pr-size-labeler@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '50'
          m_max_size: '200'
          l_max_size: '500'
          xl_label: size/xl